openapi: '3.0.1'
info:
  title: 'tendata 宠物医院'
  version: 1.0.0
servers:
  - description: SwaggerHub API Auto Mocking
    url: https://virtserver.swaggerhub.com/tendata/tendata-petclinic/1.0.0
  - url: http://localhost:8080/api
    description: Development server
  - url: https://localhost:8080/api
    description: Development server with TLS Profile
tags:
  - name: pet
    description: 宠物api
    externalDocs:
      description: 额外资料参考
      url: http://swagger.io
  - name: owner
    description: 宠物主人api
  - name: pet-type
    description: 宠物类型api
    externalDocs:
      description: 额外资料参考
      url: http://swagger.io
  - name: vet
    description: 宠物医师api
    externalDocs:
      description: 额外资料参考
      url: http://swagger.io
paths:
  /owners:
    $ref: './resources/owners.yml'
  /pets:
    $ref: './resources/pets.yml'
  /pets/{id}:
    $ref: './resources/pet.yml'
components:
  schemas:
    $ref: './schemas/component.yml'
